version: 0.0
Resources:
  - myECSService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:eu-west-3:147997142139:task-definition/nodejstask:2
        LoadBalancerInfo:
          ContainerName: nodejscontainer
          ContainerPort: 3000
